---
title: "Development Push 2.0"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Workflow Dev

Steps: 

1. Run current workflow (check it works)
2. Substitute CAMERA for gene set enrichment/
3. Ensure artifact is produced correctly 
4. Update Acceptance Test


```{r}
library(EnrichmentAnalysisStepR)
experiment_home = "/home/joseph/experiments/her_data_gsea_test"
gmt_folder = "/home/joseph/experiments/BKG_gmt_output_human/9606"

results = enrichment_workflow_step(experiment_home, 
                                   gmt_folder = gmt_folder,
                                   output_folder = file.path(experiment_home,"transform"),
                                   by = "Protein",
                                   method = "padog")
```




```{r Current comparison code}
#' Automates Enrichment Analyses on Summarized Objects for a library of gene sets
#'
#' @param comparison A summarized experiment object containing only two experimental groups
#' @param gmt_folder a folder containing gene set libraries which need to be referenced
#' @param method the method enrichment browser should use for set based enrichment
#' @return enrichment An enrichment table provided by EnrichmentBrowserPackage
#' @examples
#' sdgdfsgsf
#' @export perform_comparison_enrichment
perform_comparison_enrichment <- function(comparison, gmt_folder, method, perm = perm){

  enrichment = list()

  for (library in list.files(gmt_folder, pattern = "\\.gmt$")){
    gmt.file <- file.path(gmt_folder, library)

    gs <- getGenesets(gmt.file)

    print(gmt.file)
    print(paste("Sets in Library: ", length(gs)))
    print(paste("Genes in Library: ", length(unique(unlist(gs)))))
    print(paste("Genes in Library and dataset: ", length(intersect(rownames(comparison),unlist(gs)))))

    # check for common ids
    if (length(intersect(rownames(comparison),unlist(gs)))>100){
      
      # do enrichment      
      if (method == "camera"){
        results <- .camera(se, gs)
      } else {
        sbea.res <- sbea(method = method, se = comparison, 
                         gs = gmt.file, perm = perm, alpha = 1)
        results = as.data.frame(gsRanking(sbea.res))
        colnames(results) <- tolower(colnames(results))
      }
      
      print(colnames(results))
      # pval and gene.set must be present!
      for (col in c("gene.set", "pval")){
        stopifnot(col %in% colnames(results))
      }
      
      # write results
      lib = str_split(library,".gmt")[[1]][1]
      label = str_c(lib,"_enrichment.csv")
      
      results <- add_gene_sets_to_result(results, gs)
      results <- add_AFC_to_results(results, comparison)
      
      print(colnames(results))
      stopifnot("afc" %in% colnames(results))
      stopifnot("items" %in% colnames(results))
      
      enrichment[[lib]] = results
      
    } else {
      print("Skipping enrichment, not enough genes in common.")
      print("Heres some example ids")
      print(rownames(comparison)[1:10])
      print(unlist(gs)[1:10])
    }
    
  }
  
  enrichment
}


add_gene_sets_to_result <- function(result_table, gs){
  gene_sets <- gs2df(gs)
  result_table <- merge(result_table, gene_sets, by = "gene.set")
  result_table
}


gs2df <- function(gs){
  df <- as.data.frame(cbind(names(gs),gs))
  colnames(df) <- c("gene.set","items")
  df$gene.set <- sapply(df$gene.set, toString)
  df
}

# get's average fold change using a gene set and the SE artifact.
#' @export get_AFC
get_AFC <- function(se_comparison, gene_set){
  mean(rowData(se_comparison)[rownames(se_comparison) %in% gene_set,"FC"])
}

#' @export add_AFC_to_results
add_AFC_to_results <- function(results, se_comparison){
  results$afc <- unlist(lapply(results$items, function(x){get_AFC(se_comparison, x)}))
  results
}

.camera <- function(summarized_experiment, gene_sets){
  #Part of this code was derived from the DiscoveryBrowser package. 
  
  
  print("Running CAMERA using native code")
  
  
  # Prepare CAMERA Inputs
  expression_data <- assay(summarized_experiment)
  grp <- colData(summarized_experiment)$GROUP
  group <- factor(grp)
  f <- "~" 
  f <- formula(paste0(f, "group"))
  design <- model.matrix(f)
  
  # filter for genes in the experiment
  igenes <- intersect(rownames(expression_data), unique(unlist(gene_sets)))
  if(!length(igenes)) stop("Expression dataset (se)", " and ", 
                           "gene sets (gs) have no gene IDs in common")
  expression_data <- expression_data[igenes,]
  filtered_gene_sets <- lapply(gene_sets, function(s) s[s %in% igenes])

  
  # Call CAMERA
  gs_index <- limma::ids2indices(filtered_gene_sets, rownames(expression_data))
  camera_result <- limma::camera(expression_data, gs_index, design, sort=FALSE)
  
  # format results
  camera_result$Pathway <- rownames(camera_result)
  
  
  
  camera_result <- camera_result[, c("Pathway","PValue", "FDR","NGenes")]
  colnames(camera_result) <- c("gene.set", "pval", "adj.pval", "observed")
  
  camera_result
}

results = enrichment_workflow_step(experiment_home, 
                                   gmt_folder = gmt_folder,
                                   output_folder = file.path(experiment_home,"camera"),
                                   by = "Protein",
                                   method = "camera")

results = enrichment_workflow_step(experiment_home, 
                                   gmt_folder = gmt_folder,
                                   output_folder = file.path(experiment_home,"gsea"),
                                   by = "Protein",
                                   method = "gsea")

```


```{r Export functions}

enrichment_adjust_p_values <- function(results){
  for (condition in names(results)){
    for (library in names(results[[condition]])){
      if (!("adj.pval" %in% colnames(results[[condition]][[library]]))){
        p = results[[condition]][[library]]$pval
        results[[condition]][[library]]$adj.pval = p.adjust(p, method = "BH") 
      }
    }
  }

  results
}

#' @param results a results table producing output
#' @param gmt_folder a folder which should contain annotation csv's with details for each gmt used in enrichment
#' @return The input table with a added columns with gene set information.
#' @examples
#'
#' @export enrichment_annotate_results
enrichment_annotate_results <- function(results, gmt_folder){
  for (condition in names(results)){
    for (library in names(results[[condition]])){
      enr = results[[condition]][[library]]
      
      
      info_file = paste(gsub(".gmt","",library),"_set_info.csv", sep ="")
      if (file.exists(file.path(gmt_folder,info_file))){
        print(paste("Using set info file: ", info_file))
        info = read.csv(file.path(gmt_folder,info_file), stringsAsFactors = F)
        colnames(info) = c("gene.set", "name", "description", "items", "size", "linkout")
        if ("items" %in% colnames(info)){
          info$items <- NULL
        }
        
        enr = as.data.frame(merge(enr, info), by = "gene.set")
        
      } else {
        print(paste("Could not file info file: ", file.path(gmt_folder,info_file)))
        enr = as.data.frame(enr)
      }
      colnames(enr) <- tolower(colnames(enr))
      results[[condition]][[library]] = enr
    }
  }
  
  results
}

```







