---
title: "Mass Dynamics enrichment service"
output:
  github_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r eval=FALSE}
devtools::install_github("MassDynamics/EnrichmentAnalysisStepR")
```

```{r}
library(EnrichmentAnalysisStepR)
utils::packageVersion("EnrichmentAnalysisStepR")
```

# New enrichment workflow

## Make annotations

- Currently missing Chinese Hamster

This will build GO, Reactome for Human, Mouse, Yeast and MsigDB annotations sets for Human as internal data to the package stored in `inst/extdata`  

```{bash eval=FALSE}
make all BUILD_PACKAGE=True MSIG_VERSION="7.5"
```

List data available in the package

```{r}
extdata_path <- system.file("extdata", package = "EnrichmentAnalysisStepR")
data_files <- list.files(extdata_path, recursive = TRUE, pattern = "*rda")

data_files
```

Example load gene set. 

```{r}
load(system.file("extdata","9606/GO_human_2023-05-10.rda", package = "EnrichmentAnalysisStepR"))
head(go_sets$genesets_table)
```

## Read dataset parameters

```{r}
# example read json file
gene_sets <- list("BiologicalProcess", "MolecularFunction")
condition_comparisons <- list(list(right = "COVID", left = "MP"), 
                              list(right = "COVID", left = "Control"))
datasetParams <- list(dataset_id = "ID1", 
                      version = utils::packageVersion("EnrichmentAnalysisStepR"), 
                      fields = list(experiment_design = data.frame(), 
                                    species_gene_set_selection = list(gene_sets=gene_sets, species = "Human"), 
                                                  condition_comparisons = condition_comparisons))
```

```{r}
# create class 
datasetParams <- new("EnrichmentDatasetParameters", dataset_id = datasetParams$dataset_id,
                     version = datasetParams$dataset_id, fields = datasetParams$fields)

getConditionComparisons(datasetParams)
```

```{r}
getSpecies(datasetParams)
```

```{r}
getGeneSets(datasetParams)
```

# Run enrichment test data

```{r eval=FALSE}
intensitiesDf <- exampleData$intensitiesDf
metadataDf <- exampleData$metadataDf
paramsCovid <- exampleData$params

results <- runEnrichmentForAnnotationSet(intensitiesDf = intensitiesDf, metadataDf = metadataDf, datasetParams = paramsCovid)
```

