---
title: "Biological Investigation - HER/L-DOPA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## HER

```{r}

library(EnrichmentAnalysisStepR)
experiment_home = "/home/joseph/experiments/her_data_gsea_test"
gmt_folder = "/home/joseph/experiments/BKG_gmt_output_human/9606"

results = enrichment_workflow_step(experiment_home, 
                                   gmt_folder = gmt_folder,
                                   output_folder = file.path(experiment_home,"camera"),
                                   by = "Protein",
                                   method = "camera")
```

```{r}


plot_enr_volcano <- function(enr_table){
  p <- ggplot(enr_table, 
              aes(afc, -log10(adj.pval), fdr = adj.pval, color = observed, gene.set = gene.set, name = name)) + 
    geom_point() +
    geom_hline(yintercept=-log10(0.05)) 
  ggplotly(p)
}

plot_enr_volcano(results$`C - P`$BiologicalProcess)
plot_enr_volcano(results$`C - P`$CellularComponents)
plot_enr_volcano(results$`C - P`$MolecularFunction)
plot_enr_volcano(results$`C - P`$Reactome)
```

