---
title: "Benchmark 3 Fake Gene Sets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(plotly)
```

# Simulation Benchmarking

```{r}
experiment_home = "/home/joseph/experiments/ups_benchmark/"
upload_folder <- experiment_home
# Get Experiment Data
protein_viz_path = file.path(upload_folder,"protein_viz.json")
stopifnot(file.exists(protein_viz_path))
protein_viz = read_json(protein_viz_path, simplifyVector = TRUE)
stopifnot(dim(protein_viz)[1]>0)


protein_int_path = file.path(upload_folder,"proteinGroups_quant_intensities.txt")
if (!file.exists(protein_int_path)){
  protein_int_path = file.path(upload_folder,"Protein_Intensity.txt")
  stopifnot(file.exists(protein_int_path))
  protein_int = read.csv(protein_int_path, sep ="\t")
  protein_int = disco_protein_int_to_byo_int(protein_int)
} else {
  stopifnot(file.exists(protein_int_path))
  protein_int = read.csv(protein_int_path, sep ="\t")
}

protein_int <- get_protein_quant_intensities(protein_int)

# construct summarized experiment:
comparison = protein_viz[1,"conditionComparison"]
print(comparison)

# get protein viz data
comparison_viz = as.data.frame(protein_viz[1, "data"])

all_proteins <- comparison_viz$ProteinId
all_proteins[1:10]

head(comparison_viz)
```

```{r Get SE Comparison}
by = "Protein"
# for comparison in comparisons...
results = list()
for (row in (1:nrow(protein_viz))){
  
  # Get the Comparison
  comparison = protein_viz[row,"conditionComparison"]
  print(comparison)
  
  # get protein viz data
  comparison_viz = as.data.frame(protein_viz[row, "data"])
  
  #Get the rest of the data
  
  assay_data <- filter_int_by_viz(comparison_viz, protein_int)
  assay_data <- filter_prot_int_cols_by_comp(comparison, assay_data)
  cls_vec <- get_cls_vec(comparison, assay_data)
  se_comparison <- md_to_summarized_experiment(comparison_viz, assay_data, cls_vec, by = by)
}

```

```{r Load Spike In Data}
ups_proteins <- read.csv( "/home/joseph/experiments/ups_benchmark/UPS_benchmark.tsv", sep = "\t", stringsAsFactors = F)
ups_proteins$UPS1.Amount..fmol. <- as.numeric(gsub(",","",ups_proteins$UPS1.Amount..fmol.))
ups_proteins$UPS2.Amount..fmol. <- as.numeric(gsub(",","",ups_proteins$UPS2.Amount..fmol.))
ups_proteins$FC <- log2(ups_proteins$UPS1.Amount..fmol./ups_proteins$UPS2.Amount..fmol.)
ups_proteins$FC

very_up <- ups_proteins$UniProt.Accession.Number[ups_proteins$FC>-100]
very_up

unique(very_up)
unique(ups_proteins$FC)
```

```{r Write Fake GMT}



write_fake_gmt <- function(all_proteins, 
                           ups_proteins, 
                           path = "/home/joseph/experiments/ups_benchmark/gene_set_library/benchmark_ups.gmt",
                           spike_in_random = FALSE,
                           nested_sets = FALSE){
  
  #initialize
  gene_set_sizes <- rgeom(1000, 0.01)
  gs = list()

  if (!spike_in_random){
    all_proteins <- all_proteins[!grepl("ups", all_proteins)]
  }
  
  # write random gene sets
  for (i in 1:1000){
    n = sample(gene_set_sizes,1)
    gs[[paste("random_gene_set_",i, sep = "")]] = sample(all_proteins, n)
  }
  
  # write spike in sets
  for (FC in unique(ups_proteins$FC)){
    if (nested_sets){
      proteins = ups_proteins$UniProt.Accession.Number[ups_proteins$FC>=FC]
    } else {
      proteins = ups_proteins$UniProt.Accession.Number[ups_proteins$FC==FC]
    }
    
    gs[[paste("true_FC_gene_set_",FC, sep = "")]] = str_c(proteins,"ups")
  }
  
  print(path)
  writeGMT(gs, path)
}


write_fake_gmt(all_proteins, ups_proteins, "benchmark_ups_1.gmt")
write_fake_gmt(all_proteins, ups_proteins, "benchmark_ups_2.gmt", spike_in_random = T)
write_fake_gmt(all_proteins, ups_proteins, "benchmark_ups_3.gmt", nested_sets = T)
write_fake_gmt(all_proteins, ups_proteins, "benchmark_ups_4.gmt", 
               spike_in_random = F, nested_sets = T)
```


```{r}
experiment_home = "/home/joseph/experiments/ups_benchmark/"
gmt_folder = "/home/joseph/experiments/ups_benchmark/gene_set_library/"

results1 = enrichment_workflow_step(experiment_home, 
                                   gmt_folder = gmt_folder,
                                   output_folder = file.path(experiment_home,"gsea"),
                                   by = "Protein",
                                   method = "gsea")

results2 = enrichment_workflow_step(experiment_home, 
                                   gmt_folder = gmt_folder,
                                   output_folder = file.path(experiment_home,"padog"),
                                   by = "Protein",
                                   method = "padog")

results3 = enrichment_workflow_step(experiment_home, 
                                   gmt_folder = gmt_folder,
                                   output_folder = file.path(experiment_home,"camera"),
                                   by = "Protein",
                                   method = "camera")

```


```{r}
plot_benchmark_volcanos <- function(results){
  
  p <- ggplot(results$`UPS1 - UPS2`$benchmark_ups_1, 
              aes(gene_set = gene.set, x = afc, 
                  y = -log10(results$`UPS1 - UPS2`$benchmark_ups_1$pval))) +
    geom_point()
  p1 <- ggplotly(p)
  p <- ggplot(results$`UPS1 - UPS2`$benchmark_ups_2, 
              aes(gene_set = gene.set, x = afc, 
                  y = -log10(results$`UPS1 - UPS2`$benchmark_ups_2$pval))) +
    geom_point()
  p2 <- ggplotly(p)
  p <- ggplot(results$`UPS1 - UPS2`$benchmark_ups_3, 
              aes(gene_set = gene.set, x = afc, 
                  y = -log10(results$`UPS1 - UPS2`$benchmark_ups_3$pval))) +
    geom_point()
  p3 <- ggplotly(p)
  p <- ggplot(results$`UPS1 - UPS2`$benchmark_ups_4, 
              aes(gene_set = gene.set, x = afc, 
                  y = -log10(results$`UPS1 - UPS2`$benchmark_ups_4$pval))) +
    geom_point()
  p4<- ggplotly(p)
  
  list(p1,p2,p3,p4)
}

plot_benchmark_volcanos(results1)
```


```{r}
results = enrichment_workflow_step(experiment_home, 
                                   gmt_folder = gmt_folder,
                                   output_folder = file.path(experiment_home,"roast"),
                                   by = "Protein",
                                   method = "roast")

p <- ggplot(results$`UPS1 - UPS2`$benchmark_ups, aes(x = afc, y = -log10(results$`UPS1 - UPS2`$benchmark_ups$pval))) +
    geom_point()

ggplotly(p)
```

```{r}
colnames(both_results)
summary(lm(PValue.PROTEOMICS_INT_1/PValue ~ av_foldchange + Gene_Same, both_results))
```



```{r}
mean_dif = rowMeans(assay_data[2:5]) - rowMeans(assay_data[6:9])
std_sum = ((rowSdDiffs(assay_data[2:5]) + rowSdDiffs(assay_data[6:9])))
s2n =  mean_dif/std_sum
  
as.data.frame(cbind(assay_data$ProteinId,rank(s2n)))
plot(rank(s2n))
plot(s2n)
plot(mean_dif)
plot(rank(mean_dif))
plot(mean_dif, s2n)
```



```{r}
as.data.frame(cbind(as.character(assay_data$ProteinId),rank(s2n)))
```

